[tool.poetry]
name = "vision-test"
version = "0.1.0"
description = ""
authors = ["Binh Nguyen <b.nguyen.sn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
opencv-python = "^4.8.0.76"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
